"""Vega-Lite specification builder."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from seal_core.planner.models import ChartType

VEGA_LITE_SCHEMA = "https://vega.github.io/schema/vega-lite/v6.json"

if TYPE_CHECKING:
    from seal_sql.result import QueryResult

    from seal_charts.heuristics import HeuristicsResult


def _determine_vega_type(col_name: str, result: QueryResult) -> str:
    """Determine the Vega-Lite data type for a given column name.
    Returns 'quantitative', 'temporal', 'ordinal', or 'nominal'.
    """
    for col in result.columns:
        if col.name == col_name:
            t = col.type.lower()
            if t in (
                "integer",
                "bigint",
                "smallint",
                "decimal",
                "numeric",
                "real",
                "double precision",
                "float",
                "int",
                "int2",
                "int4",
                "int8",
                "float4",
                "float8",
            ):
                return "quantitative"
            if t in (
                "date",
                "timestamp",
                "timestamp without time zone",
                "timestamp with time zone",
            ):
                return "temporal"
            return "nominal"
    return "nominal"


def build_vega_lite_spec(
    plan_title: str, heuristics: HeuristicsResult, result: QueryResult
) -> dict[str, Any]:
    """Build a valid Vega-Lite JSON specification dictionary.

    Args:
        plan_title: Title generated by the LLM.
        heuristics: The validated ChartType and fields.
        result: The executed query result.

    Returns:
        A dictionary representing the Vega-Lite spec.
    """
    if heuristics.chart_type in (ChartType.TABLE, ChartType.METRIC_CARD):
        return {}  # No vega-lite spec for these

    x_field = heuristics.x_field
    y_field = heuristics.y_field
    color_field = heuristics.color_field

    if not x_field or not y_field:
        return {}

    x_type = _determine_vega_type(x_field, result)
    y_type = _determine_vega_type(y_field, result)

    # Base specification
    spec: dict[str, Any] = {
        "$schema": VEGA_LITE_SCHEMA,
        "title": plan_title,
        "width": "container",
        "height": "container",
        "data": {"values": result.rows},
    }

    # Mark mapping
    mark_type = "bar"
    if heuristics.chart_type == ChartType.LINE:
        mark_type = "line"
    elif heuristics.chart_type == ChartType.SCATTER:
        mark_type = "point"
    elif heuristics.chart_type == ChartType.PIE:
        mark_type = "arc"
    elif heuristics.chart_type == ChartType.AREA:
        mark_type = "area"

    # Handle pie charts differently
    if heuristics.chart_type == ChartType.PIE:
        spec["mark"] = {"type": "arc", "innerRadius": 50, "tooltip": True}
        spec["encoding"] = {
            "theta": {"field": y_field, "type": "quantitative"},
            "color": {"field": x_field, "type": "nominal"},
        }
        return spec

    # Standard marks (bar, line, point, area)
    spec["mark"] = {"type": mark_type, "tooltip": True}

    # Base Encoding
    encoding: dict[str, Any] = {
        "x": {"field": x_field, "type": x_type},
        "y": {"field": y_field, "type": y_type},
    }

    # Optional Color Encoding
    if color_field:
        c_type = _determine_vega_type(color_field, result)
        encoding["color"] = {"field": color_field, "type": c_type}

    # Formatting adjustments
    if x_type == "temporal" and heuristics.chart_type in (ChartType.LINE, ChartType.AREA):
        # Prevent temporal bar charts from overlapping if not binned
        encoding["x"]["axis"] = {"format": "%Y-%m-%d", "labelAngle": -45}

    if mark_type == "bar" and x_type == "nominal":
        encoding["x"]["axis"] = {"labelAngle": -45}

    spec["encoding"] = encoding

    return spec
